// ============================================================
// DocRx — Seed Data: Medicines, Tests, Diagnoses
// ~300 Indian medicines, ~80 tests, ~50 diagnoses
// ============================================================

export const SEED_MEDICINES = [
  // ── Analgesics / Antipyretics ──────────────────────────────
  { name: 'Paracetamol 500mg', dosage: '500mg', freq: 'TDS', instr: 'After Food', route: 'Oral' },
  { name: 'Paracetamol 650mg', dosage: '650mg', freq: 'TDS', instr: 'After Food', route: 'Oral' },
  { name: 'Ibuprofen 400mg',   dosage: '400mg', freq: 'TDS', instr: 'After Food', route: 'Oral' },
  { name: 'Ibuprofen 200mg',   dosage: '200mg', freq: 'BD',  instr: 'After Food', route: 'Oral' },
  { name: 'Diclofenac 50mg',   dosage: '50mg',  freq: 'BD',  instr: 'After Food', route: 'Oral' },
  { name: 'Diclofenac 75mg SR',dosage: '75mg',  freq: 'OD',  instr: 'After Food', route: 'Oral' },
  { name: 'Aceclofenac 100mg', dosage: '100mg', freq: 'BD',  instr: 'After Food', route: 'Oral' },
  { name: 'Nimesulide 100mg',  dosage: '100mg', freq: 'BD',  instr: 'After Food', route: 'Oral' },
  { name: 'Mefenamic Acid 500mg', dosage: '500mg', freq: 'TDS', instr: 'After Food', route: 'Oral' },
  { name: 'Tramadol 50mg',     dosage: '50mg',  freq: 'BD',  instr: 'After Food', route: 'Oral' },
  { name: 'Aspirin 75mg',      dosage: '75mg',  freq: 'OD',  instr: 'After Food', route: 'Oral' },
  { name: 'Aspirin 150mg',     dosage: '150mg', freq: 'OD',  instr: 'After Food', route: 'Oral' },
  { name: 'Ketorolac 10mg',    dosage: '10mg',  freq: 'TDS', instr: 'After Food', route: 'Oral' },

  // ── Antibiotics ───────────────────────────────────────────
  { name: 'Amoxicillin 500mg',       dosage: '500mg', freq: 'TDS', instr: 'After Food', route: 'Oral' },
  { name: 'Amoxicillin 250mg',       dosage: '250mg', freq: 'TDS', instr: 'After Food', route: 'Oral' },
  { name: 'Amoxicillin-Clavulanate 625mg', dosage: '625mg', freq: 'BD', instr: 'After Food', route: 'Oral' },
  { name: 'Amoxicillin-Clavulanate 375mg', dosage: '375mg', freq: 'TDS', instr: 'After Food', route: 'Oral' },
  { name: 'Azithromycin 500mg',      dosage: '500mg', freq: 'OD', instr: 'Empty Stomach', route: 'Oral' },
  { name: 'Azithromycin 250mg',      dosage: '250mg', freq: 'OD', instr: 'Empty Stomach', route: 'Oral' },
  { name: 'Ciprofloxacin 500mg',     dosage: '500mg', freq: 'BD', instr: 'After Food', route: 'Oral' },
  { name: 'Ciprofloxacin 250mg',     dosage: '250mg', freq: 'BD', instr: 'After Food', route: 'Oral' },
  { name: 'Levofloxacin 500mg',      dosage: '500mg', freq: 'OD', instr: 'After Food', route: 'Oral' },
  { name: 'Levofloxacin 750mg',      dosage: '750mg', freq: 'OD', instr: 'After Food', route: 'Oral' },
  { name: 'Doxycycline 100mg',       dosage: '100mg', freq: 'BD', instr: 'After Food with Water', route: 'Oral' },
  { name: 'Clarithromycin 500mg',    dosage: '500mg', freq: 'BD', instr: 'After Food', route: 'Oral' },
  { name: 'Cefixime 200mg',          dosage: '200mg', freq: 'BD', instr: 'After Food', route: 'Oral' },
  { name: 'Cephalexin 500mg',        dosage: '500mg', freq: 'QID', instr: 'After Food', route: 'Oral' },
  { name: 'Metronidazole 400mg',     dosage: '400mg', freq: 'TDS', instr: 'After Food', route: 'Oral' },
  { name: 'Tinidazole 500mg',        dosage: '500mg', freq: 'BD', instr: 'After Food', route: 'Oral' },
  { name: 'Trimethoprim-Sulfamethoxazole 960mg', dosage: '960mg', freq: 'BD', instr: 'After Food', route: 'Oral' },
  { name: 'Nitrofurantoin 100mg',    dosage: '100mg', freq: 'BD', instr: 'After Food', route: 'Oral' },
  { name: 'Erythromycin 500mg',      dosage: '500mg', freq: 'QID', instr: 'Empty Stomach', route: 'Oral' },

  // ── Antifungals ───────────────────────────────────────────
  { name: 'Fluconazole 150mg',       dosage: '150mg', freq: 'Single Dose', instr: 'As Directed', route: 'Oral' },
  { name: 'Fluconazole 50mg',        dosage: '50mg',  freq: 'OD', instr: 'After Food', route: 'Oral' },
  { name: 'Itraconazole 100mg',      dosage: '100mg', freq: 'BD', instr: 'After Food', route: 'Oral' },
  { name: 'Clotrimazole Cream 1%',   dosage: 'Thin layer', freq: 'BD', instr: 'Apply on affected area', route: 'Topical' },
  { name: 'Terbinafine 250mg',       dosage: '250mg', freq: 'OD', instr: 'After Food', route: 'Oral' },

  // ── Antivirals ────────────────────────────────────────────
  { name: 'Acyclovir 400mg',         dosage: '400mg', freq: 'TDS', instr: 'After Food', route: 'Oral' },
  { name: 'Oseltamivir 75mg',        dosage: '75mg',  freq: 'BD', instr: 'After Food', route: 'Oral' },
  { name: 'Valacyclovir 500mg',      dosage: '500mg', freq: 'BD', instr: 'After Food', route: 'Oral' },

  // ── Gastrointestinal ─────────────────────────────────────
  { name: 'Omeprazole 20mg',         dosage: '20mg',  freq: 'OD', instr: 'Before Breakfast', route: 'Oral' },
  { name: 'Omeprazole 40mg',         dosage: '40mg',  freq: 'OD', instr: 'Before Breakfast', route: 'Oral' },
  { name: 'Pantoprazole 40mg',       dosage: '40mg',  freq: 'OD', instr: 'Before Breakfast', route: 'Oral' },
  { name: 'Rabeprazole 20mg',        dosage: '20mg',  freq: 'OD', instr: 'Before Breakfast', route: 'Oral' },
  { name: 'Esomeprazole 20mg',       dosage: '20mg',  freq: 'OD', instr: 'Before Breakfast', route: 'Oral' },
  { name: 'Ranitidine 150mg',        dosage: '150mg', freq: 'BD', instr: 'After Food', route: 'Oral' },
  { name: 'Domperidone 10mg',        dosage: '10mg',  freq: 'TDS', instr: 'Before Food', route: 'Oral' },
  { name: 'Metoclopramide 10mg',     dosage: '10mg',  freq: 'TDS', instr: 'Before Food', route: 'Oral' },
  { name: 'Ondansetron 4mg',         dosage: '4mg',   freq: 'TDS', instr: 'As Directed', route: 'Oral' },
  { name: 'Ondansetron 8mg',         dosage: '8mg',   freq: 'BD', instr: 'As Directed', route: 'Oral' },
  { name: 'Loperamide 2mg',          dosage: '2mg',   freq: 'SOS', instr: 'After Loose Stools', route: 'Oral' },
  { name: 'Dicyclomine 10mg',        dosage: '10mg',  freq: 'TDS', instr: 'Before Food', route: 'Oral' },
  { name: 'Dicyclomine 20mg',        dosage: '20mg',  freq: 'TDS', instr: 'Before Food', route: 'Oral' },
  { name: 'ORS Sachets',             dosage: '1 sachet', freq: 'After each loose stool', instr: 'Dissolve in 200ml water', route: 'Oral' },
  { name: 'Lactulose 10g/15ml',      dosage: '15ml',  freq: 'BD', instr: 'With Water', route: 'Oral' },
  { name: 'Isabgol Husk',            dosage: '1 tsp', freq: 'BD', instr: 'With warm water after food', route: 'Oral' },
  { name: 'Sucralfate 1g',           dosage: '1g',    freq: 'QID', instr: 'Empty Stomach', route: 'Oral' },
  { name: 'Antacid (Gel)',           dosage: '10ml',  freq: 'TDS + HS', instr: 'After Food', route: 'Oral' },

  // ── Antidiabetics ─────────────────────────────────────────
  { name: 'Metformin 500mg',         dosage: '500mg', freq: 'BD', instr: 'After Food', route: 'Oral' },
  { name: 'Metformin 1000mg',        dosage: '1000mg', freq: 'BD', instr: 'After Food', route: 'Oral' },
  { name: 'Metformin 850mg',         dosage: '850mg', freq: 'TDS', instr: 'After Food', route: 'Oral' },
  { name: 'Glipizide 5mg',           dosage: '5mg',   freq: 'OD', instr: 'Before Breakfast', route: 'Oral' },
  { name: 'Glibenclamide 5mg',       dosage: '5mg',   freq: 'OD', instr: 'Before Breakfast', route: 'Oral' },
  { name: 'Gliclazide 80mg',         dosage: '80mg',  freq: 'BD', instr: 'Before Food', route: 'Oral' },
  { name: 'Gliclazide MR 30mg',      dosage: '30mg',  freq: 'OD', instr: 'With Breakfast', route: 'Oral' },
  { name: 'Glimepiride 1mg',         dosage: '1mg',   freq: 'OD', instr: 'Before Breakfast', route: 'Oral' },
  { name: 'Glimepiride 2mg',         dosage: '2mg',   freq: 'OD', instr: 'Before Breakfast', route: 'Oral' },
  { name: 'Sitagliptin 100mg',       dosage: '100mg', freq: 'OD', instr: 'After Food', route: 'Oral' },
  { name: 'Vildagliptin 50mg',       dosage: '50mg',  freq: 'BD', instr: 'After Food', route: 'Oral' },
  { name: 'Empagliflozin 10mg',      dosage: '10mg',  freq: 'OD', instr: 'With Breakfast', route: 'Oral' },
  { name: 'Dapagliflozin 10mg',      dosage: '10mg',  freq: 'OD', instr: 'With Breakfast', route: 'Oral' },
  { name: 'Pioglitazone 15mg',       dosage: '15mg',  freq: 'OD', instr: 'After Food', route: 'Oral' },

  // ── Antihypertensives ─────────────────────────────────────
  { name: 'Amlodipine 5mg',          dosage: '5mg',   freq: 'OD', instr: 'At Bedtime', route: 'Oral' },
  { name: 'Amlodipine 10mg',         dosage: '10mg',  freq: 'OD', instr: 'At Bedtime', route: 'Oral' },
  { name: 'Atenolol 50mg',           dosage: '50mg',  freq: 'OD', instr: 'With Breakfast', route: 'Oral' },
  { name: 'Atenolol 25mg',           dosage: '25mg',  freq: 'OD', instr: 'With Breakfast', route: 'Oral' },
  { name: 'Telmisartan 40mg',        dosage: '40mg',  freq: 'OD', instr: 'Before Breakfast', route: 'Oral' },
  { name: 'Telmisartan 80mg',        dosage: '80mg',  freq: 'OD', instr: 'Before Breakfast', route: 'Oral' },
  { name: 'Losartan 50mg',           dosage: '50mg',  freq: 'OD', instr: 'After Food', route: 'Oral' },
  { name: 'Olmesartan 20mg',         dosage: '20mg',  freq: 'OD', instr: 'After Food', route: 'Oral' },
  { name: 'Ramipril 5mg',            dosage: '5mg',   freq: 'OD', instr: 'At Bedtime', route: 'Oral' },
  { name: 'Ramipril 2.5mg',          dosage: '2.5mg', freq: 'OD', instr: 'At Bedtime', route: 'Oral' },
  { name: 'Enalapril 5mg',           dosage: '5mg',   freq: 'OD', instr: 'After Food', route: 'Oral' },
  { name: 'Hydrochlorothiazide 12.5mg', dosage: '12.5mg', freq: 'OD', instr: 'With Breakfast', route: 'Oral' },
  { name: 'Furosemide 40mg',         dosage: '40mg',  freq: 'OD', instr: 'Morning With Water', route: 'Oral' },
  { name: 'Spironolactone 25mg',     dosage: '25mg',  freq: 'OD', instr: 'After Food', route: 'Oral' },
  { name: 'Metoprolol 25mg',         dosage: '25mg',  freq: 'BD', instr: 'After Food', route: 'Oral' },
  { name: 'Metoprolol 50mg',         dosage: '50mg',  freq: 'BD', instr: 'After Food', route: 'Oral' },
  { name: 'Carvedilol 6.25mg',       dosage: '6.25mg', freq: 'BD', instr: 'After Food', route: 'Oral' },
  { name: 'Nifedipine 10mg',         dosage: '10mg',  freq: 'TDS', instr: 'After Food', route: 'Oral' },
  { name: 'Clonidine 0.1mg',         dosage: '0.1mg', freq: 'BD', instr: 'After Food', route: 'Oral' },

  // ── Lipid-lowering ────────────────────────────────────────
  { name: 'Atorvastatin 10mg',       dosage: '10mg',  freq: 'OD', instr: 'At Bedtime', route: 'Oral' },
  { name: 'Atorvastatin 20mg',       dosage: '20mg',  freq: 'OD', instr: 'At Bedtime', route: 'Oral' },
  { name: 'Atorvastatin 40mg',       dosage: '40mg',  freq: 'OD', instr: 'At Bedtime', route: 'Oral' },
  { name: 'Rosuvastatin 10mg',       dosage: '10mg',  freq: 'OD', instr: 'At Bedtime', route: 'Oral' },
  { name: 'Rosuvastatin 20mg',       dosage: '20mg',  freq: 'OD', instr: 'At Bedtime', route: 'Oral' },
  { name: 'Fenofibrate 145mg',       dosage: '145mg', freq: 'OD', instr: 'After Food', route: 'Oral' },

  // ── Respiratory ───────────────────────────────────────────
  { name: 'Salbutamol 2mg',          dosage: '2mg',   freq: 'TDS', instr: 'As Directed', route: 'Oral' },
  { name: 'Salbutamol Inhaler (100mcg)', dosage: '2 puffs', freq: 'SOS', instr: 'As Needed', route: 'Inhalation' },
  { name: 'Levosalbutamol 1mg',      dosage: '1mg',   freq: 'TDS', instr: 'After Food', route: 'Oral' },
  { name: 'Budesonide Inhaler 200mcg', dosage: '1 puff', freq: 'BD', instr: 'Rinse Mouth After Use', route: 'Inhalation' },
  { name: 'Fluticasone 125mcg Inhaler', dosage: '2 puffs', freq: 'BD', instr: 'Rinse Mouth After Use', route: 'Inhalation' },
  { name: 'Formoterol+Budesonide Inhaler', dosage: '1 puff', freq: 'BD', instr: 'As Directed', route: 'Inhalation' },
  { name: 'Montelukast 10mg',        dosage: '10mg',  freq: 'OD', instr: 'At Bedtime', route: 'Oral' },
  { name: 'Montelukast 5mg',         dosage: '5mg',   freq: 'OD', instr: 'At Bedtime', route: 'Oral' },
  { name: 'Levocetrizine 5mg',       dosage: '5mg',   freq: 'OD', instr: 'At Bedtime', route: 'Oral' },
  { name: 'Cetirizine 10mg',         dosage: '10mg',  freq: 'OD', instr: 'At Bedtime', route: 'Oral' },
  { name: 'Fexofenadine 120mg',      dosage: '120mg', freq: 'OD', instr: 'Before Food', route: 'Oral' },
  { name: 'Fexofenadine 180mg',      dosage: '180mg', freq: 'OD', instr: 'Before Food', route: 'Oral' },
  { name: 'Chlorpheniramine 4mg',    dosage: '4mg',   freq: 'TDS', instr: 'After Food', route: 'Oral' },
  { name: 'Dextromethorphan 15mg',   dosage: '15mg',  freq: 'TDS', instr: 'After Food', route: 'Oral' },
  { name: 'Ambroxol 30mg',           dosage: '30mg',  freq: 'TDS', instr: 'After Food', route: 'Oral' },
  { name: 'Bromhexine 8mg',          dosage: '8mg',   freq: 'TDS', instr: 'After Food', route: 'Oral' },
  { name: 'Guaifenesin 200mg',       dosage: '200mg', freq: 'TDS', instr: 'With Water', route: 'Oral' },
  { name: 'Ipratropium Inhaler 20mcg', dosage: '2 puffs', freq: 'QID', instr: 'As Directed', route: 'Inhalation' },
  { name: 'Prednisolone 5mg',        dosage: '5mg',   freq: 'OD', instr: 'After Breakfast', route: 'Oral' },
  { name: 'Prednisolone 10mg',       dosage: '10mg',  freq: 'OD', instr: 'After Breakfast', route: 'Oral' },
  { name: 'Methylprednisolone 4mg',  dosage: '4mg',   freq: 'TDS', instr: 'After Food', route: 'Oral' },

  // ── Vitamins & Supplements ────────────────────────────────
  { name: 'Vitamin D3 60000 IU',     dosage: '60000 IU', freq: 'Once Weekly', instr: 'After Food', route: 'Oral' },
  { name: 'Vitamin D3 1000 IU',      dosage: '1000 IU', freq: 'OD', instr: 'After Food', route: 'Oral' },
  { name: 'Calcium + Vitamin D3',    dosage: '1 tablet', freq: 'BD', instr: 'After Food', route: 'Oral' },
  { name: 'Folic Acid 5mg',          dosage: '5mg',   freq: 'OD', instr: 'After Food', route: 'Oral' },
  { name: 'Iron + Folic Acid',       dosage: '1 tablet', freq: 'OD', instr: 'Empty Stomach', route: 'Oral' },
  { name: 'Ferrous Sulphate 200mg',  dosage: '200mg', freq: 'BD', instr: 'Empty Stomach', route: 'Oral' },
  { name: 'Vitamin B12 500mcg',      dosage: '500mcg', freq: 'OD', instr: 'After Food', route: 'Oral' },
  { name: 'Vitamin B Complex',       dosage: '1 tablet', freq: 'OD', instr: 'After Food', route: 'Oral' },
  { name: 'Vitamin C 500mg',         dosage: '500mg', freq: 'OD', instr: 'After Food', route: 'Oral' },
  { name: 'Zinc 50mg',               dosage: '50mg',  freq: 'OD', instr: 'After Food', route: 'Oral' },
  { name: 'Omega-3 1000mg',          dosage: '1000mg', freq: 'OD', instr: 'After Food', route: 'Oral' },
  { name: 'Multivitamin + Multimineral', dosage: '1 tablet', freq: 'OD', instr: 'After Breakfast', route: 'Oral' },
  { name: 'Magnesium 250mg',         dosage: '250mg', freq: 'OD', instr: 'At Bedtime', route: 'Oral' },

  // ── Thyroid ───────────────────────────────────────────────
  { name: 'Levothyroxine 25mcg',     dosage: '25mcg', freq: 'OD', instr: 'Empty Stomach 30min Before Breakfast', route: 'Oral' },
  { name: 'Levothyroxine 50mcg',     dosage: '50mcg', freq: 'OD', instr: 'Empty Stomach 30min Before Breakfast', route: 'Oral' },
  { name: 'Levothyroxine 75mcg',     dosage: '75mcg', freq: 'OD', instr: 'Empty Stomach 30min Before Breakfast', route: 'Oral' },
  { name: 'Levothyroxine 100mcg',    dosage: '100mcg', freq: 'OD', instr: 'Empty Stomach 30min Before Breakfast', route: 'Oral' },
  { name: 'Carbimazole 5mg',         dosage: '5mg',   freq: 'TDS', instr: 'After Food', route: 'Oral' },

  // ── Neurological / Pain ───────────────────────────────────
  { name: 'Gabapentin 300mg',        dosage: '300mg', freq: 'TDS', instr: 'After Food', route: 'Oral' },
  { name: 'Pregabalin 75mg',         dosage: '75mg',  freq: 'BD', instr: 'After Food', route: 'Oral' },
  { name: 'Pregabalin 150mg',        dosage: '150mg', freq: 'BD', instr: 'After Food', route: 'Oral' },
  { name: 'Amitriptyline 10mg',      dosage: '10mg',  freq: 'OD', instr: 'At Bedtime', route: 'Oral' },
  { name: 'Clonazepam 0.25mg',       dosage: '0.25mg', freq: 'OD', instr: 'At Bedtime', route: 'Oral' },
  { name: 'Alprazolam 0.25mg',       dosage: '0.25mg', freq: 'OD', instr: 'At Bedtime', route: 'Oral' },
  { name: 'Escitalopram 10mg',       dosage: '10mg',  freq: 'OD', instr: 'After Breakfast', route: 'Oral' },
  { name: 'Sertraline 50mg',         dosage: '50mg',  freq: 'OD', instr: 'After Food', route: 'Oral' },
  { name: 'Fluoxetine 20mg',         dosage: '20mg',  freq: 'OD', instr: 'After Breakfast', route: 'Oral' },
  { name: 'Phenytoin 100mg',         dosage: '100mg', freq: 'BD', instr: 'After Food', route: 'Oral' },
  { name: 'Valproate 200mg',         dosage: '200mg', freq: 'TDS', instr: 'After Food', route: 'Oral' },
  { name: 'Levetiracetam 500mg',     dosage: '500mg', freq: 'BD', instr: 'After Food', route: 'Oral' },

  // ── Muscle Relaxants ──────────────────────────────────────
  { name: 'Chlorzoxazone 500mg',     dosage: '500mg', freq: 'TDS', instr: 'After Food', route: 'Oral' },
  { name: 'Thiocolchicoside 4mg',    dosage: '4mg',   freq: 'BD', instr: 'After Food', route: 'Oral' },
  { name: 'Baclofen 10mg',           dosage: '10mg',  freq: 'TDS', instr: 'After Food', route: 'Oral' },

  // ── Urology ───────────────────────────────────────────────
  { name: 'Tamsulosin 0.4mg',        dosage: '0.4mg', freq: 'OD', instr: '30 Min After Breakfast', route: 'Oral' },
  { name: 'Finasteride 5mg',         dosage: '5mg',   freq: 'OD', instr: 'After Food', route: 'Oral' },
  { name: 'Oxybutynin 5mg',          dosage: '5mg',   freq: 'BD', instr: 'After Food', route: 'Oral' },
  { name: 'Solifenacin 5mg',         dosage: '5mg',   freq: 'OD', instr: 'After Food', route: 'Oral' },

  // ── Dermatology ───────────────────────────────────────────
  { name: 'Betamethasone Cream 0.1%', dosage: 'Thin layer', freq: 'BD', instr: 'Apply on affected area', route: 'Topical' },
  { name: 'Hydrocortisone Cream 1%',  dosage: 'Thin layer', freq: 'BD', instr: 'Apply on affected area', route: 'Topical' },
  { name: 'Mupirocin Ointment 2%',    dosage: 'Thin layer', freq: 'TDS', instr: 'Apply on affected area', route: 'Topical' },
  { name: 'Permethrin Cream 5%',      dosage: 'Apply all over', freq: 'Single application', instr: 'Wash off after 8 hrs', route: 'Topical' },
  { name: 'Calamine Lotion',          dosage: 'As required', freq: 'TDS', instr: 'Apply on affected area', route: 'Topical' },
  { name: 'Tretinoin Cream 0.025%',   dosage: 'Pea size', freq: 'OD', instr: 'Apply at night on affected area', route: 'Topical' },

  // ── Ophthalmology ─────────────────────────────────────────
  { name: 'Ciprofloxacin Eye Drops 0.3%', dosage: '1-2 drops', freq: 'QID', instr: 'In affected eye(s)', route: 'Drops' },
  { name: 'Tobramycin Eye Drops 0.3%', dosage: '1-2 drops', freq: 'QID', instr: 'In affected eye(s)', route: 'Drops' },
  { name: 'Sodium Chloride Eye Drops 0.9%', dosage: '1-2 drops', freq: 'QID', instr: 'In affected eye(s)', route: 'Drops' },
  { name: 'Carboxymethylcellulose Eye Drops', dosage: '1-2 drops', freq: 'QID-SOS', instr: 'In affected eye(s)', route: 'Drops' },
  { name: 'Prednisolone Eye Drops 1%', dosage: '1-2 drops', freq: 'QID', instr: 'In affected eye(s)', route: 'Drops' },

  // ── Antiparasitics / Deworming ────────────────────────────
  { name: 'Albendazole 400mg',       dosage: '400mg', freq: 'Single Dose', instr: 'With Food', route: 'Oral' },
  { name: 'Ivermectin 12mg',         dosage: '12mg',  freq: 'Single Dose', instr: 'Empty Stomach', route: 'Oral' },
  { name: 'Mebendazole 100mg',       dosage: '100mg', freq: 'BD for 3 days', instr: 'With Food', route: 'Oral' },

  // ── Miscellaneous / Common ────────────────────────────────
  { name: 'Pantoprazole + Domperidone', dosage: '1 tablet', freq: 'BD', instr: 'Before Food', route: 'Oral' },
  { name: 'Aceclofenac + Paracetamol', dosage: '1 tablet', freq: 'BD', instr: 'After Food', route: 'Oral' },
  { name: 'Diclofenac + Paracetamol', dosage: '1 tablet', freq: 'TDS', instr: 'After Food', route: 'Oral' },
  { name: 'Paracetamol + Caffeine',   dosage: '1 tablet', freq: 'SOS', instr: 'After Food', route: 'Oral' },
  { name: 'Activated Charcoal 250mg', dosage: '250mg', freq: 'TDS', instr: 'After Food', route: 'Oral' },
  { name: 'Dimethicone 40mg',         dosage: '40mg',  freq: 'TDS after food + HS', instr: 'After Food', route: 'Oral' },
  { name: 'Syrup Ambroxol 15mg/5ml',  dosage: '10ml',  freq: 'TDS', instr: 'After Food', route: 'Oral' },
  { name: 'Syrup Paracetamol 120mg/5ml', dosage: '5ml', freq: 'TDS', instr: 'After Food', route: 'Oral' },
  { name: 'Injection Diclofenac 75mg/3ml', dosage: '75mg', freq: 'SOS', instr: 'Deep IM', route: 'Injection' },
  { name: 'Injection Ondansetron 4mg', dosage: '4mg', freq: 'SOS', instr: 'IV Slow', route: 'Injection' },
];

export const SEED_TESTS = [
  // Haematology
  { name: 'Complete Blood Count (CBC)', instr: 'No fasting required' },
  { name: 'Haemoglobin (Hb)', instr: 'No fasting required' },
  { name: 'Erythrocyte Sedimentation Rate (ESR)', instr: 'No fasting required' },
  { name: 'Peripheral Blood Smear', instr: 'No fasting required' },
  { name: 'Reticulocyte Count', instr: 'No fasting required' },
  { name: 'Platelet Count', instr: 'No fasting required' },
  { name: 'Prothrombin Time (PT/INR)', instr: 'No fasting required' },
  { name: 'APTT', instr: 'No fasting required' },
  { name: 'Bleeding Time / Clotting Time', instr: 'No fasting required' },
  { name: 'Blood Group & Rh Typing', instr: 'No fasting required' },

  // Biochemistry
  { name: 'Fasting Blood Sugar (FBS)', instr: '8-10 hours fasting required' },
  { name: 'Post-Prandial Blood Sugar (PPBS)', instr: '2 hours after meal' },
  { name: 'Random Blood Sugar (RBS)', instr: 'No fasting required' },
  { name: 'HbA1c', instr: 'No fasting required' },
  { name: 'Fasting Lipid Profile', instr: '10-12 hours fasting required' },
  { name: 'Total Cholesterol', instr: '10-12 hours fasting required' },
  { name: 'LDL Cholesterol', instr: '10-12 hours fasting required' },
  { name: 'HDL Cholesterol', instr: 'No fasting required' },
  { name: 'Triglycerides', instr: '10-12 hours fasting required' },
  { name: 'Blood Urea Nitrogen (BUN)', instr: 'No fasting required' },
  { name: 'Serum Creatinine', instr: 'No fasting required' },
  { name: 'Uric Acid', instr: 'No fasting required' },
  { name: 'Liver Function Tests (LFT)', instr: '4-6 hours fasting preferred' },
  { name: 'SGPT (ALT)', instr: 'No fasting required' },
  { name: 'SGOT (AST)', instr: 'No fasting required' },
  { name: 'Serum Bilirubin Total/Direct', instr: 'No fasting required' },
  { name: 'Alkaline Phosphatase (ALP)', instr: 'No fasting required' },
  { name: 'Gamma-GT (GGT)', instr: 'No fasting required' },
  { name: 'Serum Albumin', instr: 'No fasting required' },
  { name: 'Kidney Function Tests (KFT)', instr: 'No fasting required' },
  { name: 'Electrolytes (Na, K, Cl)', instr: 'No fasting required' },
  { name: 'Serum Calcium', instr: 'No fasting required' },
  { name: 'Serum Phosphorus', instr: 'No fasting required' },
  { name: 'Serum Magnesium', instr: 'No fasting required' },
  { name: 'Vitamin D (25-OH)', instr: 'No fasting required' },
  { name: 'Vitamin B12', instr: 'No fasting required' },
  { name: 'Serum Ferritin', instr: 'No fasting required' },
  { name: 'Serum Iron & TIBC', instr: 'Morning sample preferred' },
  { name: 'C-Reactive Protein (CRP)', instr: 'No fasting required' },
  { name: 'Procalcitonin (PCT)', instr: 'No fasting required' },
  { name: 'D-Dimer', instr: 'No fasting required' },
  { name: 'Serum Protein Total', instr: 'No fasting required' },
  { name: 'VDRL', instr: 'No fasting required' },

  // Thyroid
  { name: 'Thyroid Stimulating Hormone (TSH)', instr: 'Morning sample preferred' },
  { name: 'Free T3 (fT3)', instr: 'Morning sample preferred' },
  { name: 'Free T4 (fT4)', instr: 'Morning sample preferred' },
  { name: 'Thyroid Profile (T3, T4, TSH)', instr: 'Morning sample preferred' },
  { name: 'Anti-TPO Antibodies', instr: 'No fasting required' },

  // Urine
  { name: 'Urine Routine & Microscopy', instr: 'Midstream morning sample' },
  { name: 'Urine Culture & Sensitivity', instr: 'Midstream clean-catch sample' },
  { name: 'Spot Urine Protein/Creatinine Ratio', instr: 'Random urine sample' },
  { name: '24-Hour Urine Protein', instr: 'Collect all urine for 24 hours' },
  { name: 'Urine Pregnancy Test (UPT)', instr: 'Morning first-void urine' },

  // Microbiology / Infection
  { name: 'Blood Culture & Sensitivity', instr: 'Collect before antibiotics if possible' },
  { name: 'Throat Swab Culture', instr: 'Before antibiotics' },
  { name: 'Sputum Culture & Sensitivity', instr: 'Early morning sputum sample' },
  { name: 'Dengue NS1 Antigen', instr: 'No fasting required' },
  { name: 'Dengue IgM/IgG', instr: 'No fasting required' },
  { name: 'Malaria Antigen Test (PF/PV)', instr: 'No fasting required' },
  { name: 'Widal Test', instr: 'No fasting required' },
  { name: 'Typhidot (IgM)', instr: 'No fasting required' },
  { name: 'HIV 1 & 2 ELISA', instr: 'No fasting required' },
  { name: 'HBsAg', instr: 'No fasting required' },
  { name: 'Anti-HCV', instr: 'No fasting required' },
  { name: 'H. Pylori Antigen (Stool)', instr: 'Stool sample required' },
  { name: 'Stool Routine & Culture', instr: 'Fresh stool sample' },

  // Cardiology
  { name: 'ECG (12-Lead)', instr: 'No fasting required. Rest for 5 min before test.' },
  { name: 'Troponin I/T', instr: 'No fasting required' },
  { name: 'CPK-MB', instr: 'No fasting required' },
  { name: 'BNP / NT-proBNP', instr: 'No fasting required' },
  { name: '2D Echo', instr: 'No fasting required' },
  { name: 'Stress Test (TMT)', instr: 'Light meal 2 hours before. Comfortable shoes.' },
  { name: 'Holter Monitor (24hr)', instr: 'Avoid bathing, sweating heavily' },

  // Radiology / Imaging
  { name: 'X-Ray Chest PA', instr: 'No preparation required' },
  { name: 'X-Ray KUB', instr: 'No preparation required' },
  { name: 'X-Ray Spine (Lumbar AP+Lat)', instr: 'No preparation required' },
  { name: 'Ultrasound Abdomen & Pelvis', instr: 'Full bladder — drink 4 glasses of water 1 hour before' },
  { name: 'Ultrasound Abdomen', instr: '6 hours fasting required' },
  { name: 'Ultrasound Thyroid', instr: 'No preparation required' },
  { name: 'CT Scan Brain (Plain)', instr: 'No preparation required' },
  { name: 'CT Chest', instr: 'No preparation required' },
  { name: 'CT Abdomen & Pelvis (with contrast)', instr: '4-6 hours fasting. Creatinine required.' },
  { name: 'MRI Brain', instr: 'Remove all metal objects. 4 hours fasting for contrast.' },
  { name: 'MRI Spine', instr: 'Remove all metal objects.' },
  { name: 'MRI Knee', instr: 'Remove all metal objects.' },
];

export const SEED_DIAGNOSES = [
  'Viral Fever', 'Dengue Fever', 'Malaria', 'Typhoid Fever', 'Chikungunya',
  'Upper Respiratory Tract Infection (URTI)', 'Lower Respiratory Tract Infection (LRTI)',
  'Community-Acquired Pneumonia', 'Bronchitis (Acute)', 'Bronchial Asthma',
  'COPD Exacerbation', 'Allergic Rhinitis', 'Sinusitis',
  'Pharyngitis', 'Tonsillitis', 'Otitis Media',
  'Gastroenteritis (Acute)', 'Diarrhoea (Acute)', 'Irritable Bowel Syndrome (IBS)',
  'Gastro-Oesophageal Reflux Disease (GERD)', 'Peptic Ulcer Disease',
  'Constipation', 'Appendicitis', 'Jaundice', 'Hepatitis B', 'Hepatitis C',
  'Urinary Tract Infection (UTI)', 'Pyelonephritis', 'Renal Colic (Urolithiasis)',
  'Type 2 Diabetes Mellitus', 'Type 1 Diabetes Mellitus',
  'Hypertension (Primary)', 'Hypertensive Urgency', 'Dyslipidaemia',
  'Hypothyroidism', 'Hyperthyroidism', 'Thyroiditis',
  'Iron Deficiency Anaemia', 'Vitamin B12 Deficiency', 'Vitamin D Deficiency',
  'Migraine', 'Tension Headache', 'Trigeminal Neuralgia',
  'Back Pain (Non-specific)', 'Lumbar Disc Prolapse', 'Cervical Spondylosis',
  'Osteoarthritis (Knee)', 'Rheumatoid Arthritis', 'Gout',
  'Scabies', 'Fungal Infection (Tinea)', 'Cellulitis', 'Contact Dermatitis', 'Eczema',
  'Conjunctivitis', 'Stye (Hordeolum)',
  'Anxiety Disorder', 'Major Depressive Disorder', 'Insomnia',
  'Epilepsy', 'Febrile Seizure', 'Vertigo (BPPV)',
  'Angina Pectoris', 'Palpitations', 'Atrial Fibrillation',
  'Pre-eclampsia', 'Antenatal Care Visit', 'Polycystic Ovary Syndrome (PCOS)',
  'Benign Prostatic Hyperplasia (BPH)', 'Erectile Dysfunction',
  'Dehydration', 'Electrolyte Imbalance', 'Sepsis (Suspected)',
  'COVID-19', 'Post-COVID Fatigue Syndrome',
  'Healthy (Routine Check-up)', 'Follow-up Visit',
];
